### PR TITLE
Make game into a game

### LINKED ISSUE #17: Game: Fix playability issues in the prototype
The game is still in a draft stage and has important flaws: 
- Incorrect bounce physics
- No bounds checking for paddle motion
- Paddle hitbox doesn't match the mesh exactly

### LINKED ISSUE #18: Game: differentiate the game stages
Right now, the game is in a continuous loop of passing the ball back and forth, but we need clear and interactive transitions between starting a game, finishing a game, scoring points, etc.

### PR DESCRIPTION
**Pull request by cpireyre**
Refactored core architecture:
  - Added state machine: START → PLAYING → GAME_OVER  (Resolves #18)
  - Tidied up a lot of code (created Game object, moved Babylon init code away)

  New features:
  - Score tracking with first-to-11 win condition
  - HTML overlay for live scores and game state messages
  - Start screen with controls, game-over screen with winner announcement
  - POST scores to endpoint when game ends. Mock endpoint for now

  Gameplay improvements:
  - Use delta time when moving ball
  - Compute bouncing angle the right way (Resolves #17)
  - Stop paddles going out of bounds (Resolves #17)

  The game is now mostly playable.

### CODE REVIEW

File: game/game.js [hunk 1]
```diff
@@ -1,129 +1,200 @@
...
+const PLAYING_FIELD_WIDTH  = 20;
+const PLAYING_FIELD_HEIGHT = 15;
+
+const States = Object.freeze({
+  START:      Symbol('start'),
+  PLAYING:    Symbol('playing'),
+  GAME_OVER:  Symbol('game_over'),
+});
+G = {
+  height: PLAYING_FIELD_WIDTH, width: PLAYING_FIELD_WIDTH,
```
Comment (miladrahmat) [inline game/game.js]: There is `PLAYING_FIELD_WIDTH` on both `height` and `width`.

**Comment by cpireyre** [comment]
Thank you very much for the feedback, I will make changes later today before the meeting

File: game/game.js [hunk 2]
```diff
@@ -1,129 +1,223 @@
...
-BALL_DIAMETER = 1;
-
-function intersect(ball, box) {
-  const x = Math.max(box.minX, Math.min(ball.x, box.maxX));
-  const z = Math.max(box.minZ, Math.min(ball.z, box.maxZ));
+"use strict mode";
+
+const PLAYING_FIELD_WIDTH  = 20;
+const PLAYING_FIELD_HEIGHT = 15;
+const WINNING_SCORE        = 2; // 11 for real gameplay
```
Comment (hpirkola) [inline game/game.js]: This could be changed to 11
